name: GetScreen Windows (6H)

on:
 workflow_dispatch:

jobs:
   build:
     runs-on: windows-latest

     steps:
     - name: Downloading & Setting Up
       run: |
         echo "EMAIL_SECRET=h31365202@icloud.com" > secrets.txt
         Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Guihenrique0101/Guilherme/main/down.bat" -OutFile "down.bat"
         cmd /c down.bat

     - name: Time Counter
       run: python time.py
